name: Build and Push Docker Image

on:
  push:
    paths:
      - '**'       # Trigger on any changes (you can restrict this later)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t pmcro/wiz-technical-project:latest .
        docker push pmcro/wiz-technical-project:latest
